In [2]:
import tensorflow as tf

In [3]:
tensor_zero_dim = tf.constant(42)
print("0-D Tensor (Scalar):")
print(tensor_zero_dim)

0-D Tensor (Scalar):
tf.Tensor(42, shape=(), dtype=int32)


In [4]:
tensor_one_dim = tf.constant([1, 2, 3, 4, 5])
print("\n1-D Tensor (Vector):")
print(tensor_one_dim)


1-D Tensor (Vector):
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [7]:
tensor_two_dim = tf.constant([[1, 2.9, 3], [4, 5.8, 6], [7, 8, 9],[10, 11, 12]])
print("\n2-D Tensor (Matrix):")
print(tensor_two_dim)


2-D Tensor (Matrix):
tf.Tensor(
[[ 1.   2.9  3. ]
 [ 4.   5.8  6. ]
 [ 7.   8.   9. ]
 [10.  11.  12. ]], shape=(4, 3), dtype=float32)


In [8]:
tensor_three_dim = tf.constant([[[1, 2,7], [3, 4,9]], [[5, 6,7], [7, 8,8]], [[9, 10,11], [11, 12,12]]])
print("\n3-D Tensor:")
print(tensor_three_dim)


3-D Tensor:
tf.Tensor(
[[[ 1  2  7]
  [ 3  4  9]]

 [[ 5  6  7]
  [ 7  8  8]]

 [[ 9 10 11]
  [11 12 12]]], shape=(3, 2, 3), dtype=int32)


In [9]:
print(tensor_three_dim.shape)  # Output: (3, 2, 3)

(3, 2, 3)


In [10]:
tensor_four_dim = tf.constant([[[[1], [2]], [[3], [4]]],
                               [[[5], [6]], [[7], [8]]],
                                [[[9], [10]], [[11], [12]]],
                                [[[13], [14]], [[15], [16]]]])

print("\n4-D Tensor:")
print(tensor_four_dim)


4-D Tensor:
tf.Tensor(
[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]]


 [[[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]]], shape=(4, 2, 2, 1), dtype=int32)


In [11]:
# now i need a 4,3,3,2 tensor
tensor_five_dim = tf.constant([[[[1, 2], [3, 4], [5, 6]],
                                 [[7, 8], [9, 10], [11, 12]],
                                 [[13, 14], [15, 16], [17, 18]]],
                                
                                [[[19, 20], [21, 22], [23, 24]],
                                 [[25, 26], [27, 28], [29, 30]],
                                 [[31, 32], [33, 34], [35, 36]]],
                                
                                [[[37, 38], [39, 40], [41, 42]],
                                 [[43, 44], [45, 46], [47, 48]],
                                 [[49, 50], [51, 52], [53, 54]]],
                                
                                [[[55, 56], [57, 58], [59, 60]],
                                 [[61, 62], [63, 64], [65, 66]],
                                 [[67, 68], [69, 70], [71, 72]]]])

print("\n5-D Tensor:")
print(tensor_five_dim)
print(tensor_five_dim.shape)  # Output: (4, 3, 3, 2)


5-D Tensor:
tf.Tensor(
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]

  [[13 14]
   [15 16]
   [17 18]]]


 [[[19 20]
   [21 22]
   [23 24]]

  [[25 26]
   [27 28]
   [29 30]]

  [[31 32]
   [33 34]
   [35 36]]]


 [[[37 38]
   [39 40]
   [41 42]]

  [[43 44]
   [45 46]
   [47 48]]

  [[49 50]
   [51 52]
   [53 54]]]


 [[[55 56]
   [57 58]
   [59 60]]

  [[61 62]
   [63 64]
   [65 66]]

  [[67 68]
   [69 70]
   [71 72]]]], shape=(4, 3, 3, 2), dtype=int32)
(4, 3, 3, 2)


In [12]:
# now i need a 4,3,2,3  tensor
tensor_six_dim = tf.constant([[[[1, 2, 3], [4, 5, 6]],
                                 [[7, 8, 9], [10, 11, 12]],
                                 [[13, 14, 15], [16, 17, 18]]],
                                
                                [[[19, 20, 21], [22, 23, 24]],
                                 [[25, 26, 27], [28, 29, 30]],
                                 [[31, 32, 33], [34, 35, 36]]],
                                
                                [[[37, 38, 39], [40, 41, 42]],
                                 [[43, 44, 45], [46, 47, 48]],
                                 [[49, 50, 51], [52, 53, 54]]],
                                
                                [[[55, 56, 57], [58, 59, 60]],
                                 [[61, 62, 63], [64, 65, 66]],
                                 [[67, 68, 69], [70, 71, 72]]]])

print("\n6-D Tensor:")
print(tensor_six_dim)


6-D Tensor:
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]]

  [[25 26 27]
   [28 29 30]]

  [[31 32 33]
   [34 35 36]]]


 [[[37 38 39]
   [40 41 42]]

  [[43 44 45]
   [46 47 48]]

  [[49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]]

  [[61 62 63]
   [64 65 66]]

  [[67 68 69]
   [70 71 72]]]], shape=(4, 3, 2, 3), dtype=int32)


In [13]:
# boolean tensor
bool_tensor = tf.constant([[True, False, True], [False, True, False]])
print("\nBoolean Tensor:")
print(bool_tensor)


Boolean Tensor:
tf.Tensor(
[[ True False  True]
 [False  True False]], shape=(2, 3), dtype=bool)


In [15]:
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)
print("\nNumPy Array:")
print(numpy_array)
print("\nTensor from NumPy Array:")
print(tensor_from_numpy)


NumPy Array:
[[1 2 3]
 [4 5 6]]

Tensor from NumPy Array:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [16]:
eye_tensor = tf.eye(num_rows=4, num_columns=4,dtype=tf.dtypes.float32,name=None)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [17]:
fill_tensor = tf.fill(dims=[3, 4], value=9)
print(fill_tensor)

tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(3, 4), dtype=int32)


In [19]:
# printing size of all our ternsors
print("\nTensor Sizes:  ")
print("0-D Tensor size:", tf.size(tensor_zero_dim).numpy())
print("1-D Tensor size:", tf.size(tensor_one_dim).numpy())
print("2-D Tensor size:", tf.size(tensor_two_dim).numpy())
print("3-D Tensor size:", tf.size(tensor_three_dim).numpy())
print("4-D Tensor size:", tf.size(tensor_four_dim).numpy())
print("5-D Tensor size:", tf.size(tensor_five_dim).numpy())
print("6-D Tensor size:", tf.size(tensor_six_dim).numpy())


Tensor Sizes:  
0-D Tensor size: 1
1-D Tensor size: 5
2-D Tensor size: 12
3-D Tensor size: 18
4-D Tensor size: 16
5-D Tensor size: 72
6-D Tensor size: 72


In [22]:
# random tensor
random_tensor = tf.random.uniform(shape=(3, 4), minval=0, maxval=10, dtype=tf.dtypes.float32, seed=42)
print("\nRandom Tensor:")
print(random_tensor)


Random Tensor:
tf.Tensor(
[[9.320633   2.7770889  3.7354589  1.3526726 ]
 [7.2929945  0.96167207 7.5067434  4.9792504 ]
 [4.8544526  2.357874   3.1611419  8.261269  ]], shape=(3, 4), dtype=float32)


### Tensor indexing

In [23]:
tensor_indexed = tf.constant([3,6,7,8,9,12,66,32,45,23,11,5])
print(tensor_indexed)
print(tensor_indexed[3])  # Accessing the 4th element (index 3)
print(tensor_indexed[0:5])  # Slicing the first 5 elements
print(tensor_indexed[-1])  # Accessing the last element
print(tensor_indexed[::2])  # Slicing with a step of 2

tf.Tensor([ 3  6  7  8  9 12 66 32 45 23 11  5], shape=(12,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([3 6 7 8 9], shape=(5,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([ 3  7  9 66 45 11], shape=(6,), dtype=int32)


In [24]:
# indexing a 2 dim tensor
tensor_2d = tf.constant([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(tensor_2d)
print(tensor_2d[1, 2])  # Accessing element at row 1, column 2
print(tensor_2d[0:2, 1:3])  # Slicing rows 0-1 and columns 1-2

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor(60, shape=(), dtype=int32)
tf.Tensor(
[[20 30]
 [50 60]], shape=(2, 2), dtype=int32)


In [28]:
# indexing a 3 dim tensor
tensor_3d = tf.constant([[[1, 2, 3], [4, 5, 6]],
                         [[7, 8, 9], [10, 11, 12]],
                         [[13, 14, 15], [16, 17, 18]]])

print(tensor_3d)
print("=============================")
print(tensor_3d[1, 0, 1])  # Accessing element at block 1, row 0, column 2
print("=============================")
print(tensor_3d[ :, 1, :])  # Slicing all blocks, row 1, all columns
print("=============================")
# print(tensor_3d)
# so how dow i index to get element 9
print(tensor_3d[1, 0, 2])  # Accessing element at block 1, row 0, column 3
print("=============================")
# so how dow i index to get element 11
print(tensor_3d[1, 1, 1])  # Accessing element at block 1, row 1, column 2
print("=============================")

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(
[[ 4  5  6]
 [10 11 12]
 [16 17 18]], shape=(3, 3), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)


In [30]:
# indexing a 4 dim tensor
tensor_4d = tf.constant([[[[1,2,3,4], [5,6,7,8], [9,10,11,12]],
                           [[13,14,15,16], [17,18,19,20], [21,22,23,24]],
                           [[25,26,27,28], [29,30,31,32], [33,34,35,36]]]])

print(tensor_4d)
print("=============================")
print(tensor_4d[0, 1, 2, 3])  # Accessing element at block 0, matrix 1, row 2, column 3
print("=============================")
print(tensor_4d[0, :, 1, :])  # Slicing block 0, all matrices, row 1, all columns
print("=============================")
print(tensor_4d[0, 2, 0, 1])  # Accessing element at block 0, matrix 2, row 0, column 1
print("=============================")
print(tensor_4d[0, 1, :, 2])  # S

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]

  [[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]]], shape=(1, 3, 3, 4), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)
tf.Tensor(
[[ 5  6  7  8]
 [17 18 19 20]
 [29 30 31 32]], shape=(3, 4), dtype=int32)
tf.Tensor(26, shape=(), dtype=int32)
tf.Tensor([15 19 23], shape=(3,), dtype=int32)
