# TensorFlow Basics: Tensors, Variables, and Mathematical Operations

This notebook demonstrates fundamental TensorFlow concepts including:
- Tensor creation and manipulation
- Variables vs constants
- Basic mathematical operations
- Linear algebra operations
- Statistical operations
- Activation functions
- Broadcasting and reshaping

Let's start by exploring TensorFlow tensors and mathematical operations step by step.

In [3]:
import tensorflow as tf

## 1. Setting Up TensorFlow Environment

First, let's import TensorFlow and check its version. TensorFlow 2.x uses eager execution by default, which makes it easier to debug and work with tensors interactively.

In [4]:
# Check TensorFlow version and GPU availability
print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {tf.config.list_physical_devices('GPU')}")
print(f"Built with CUDA: {tf.test.is_built_with_cuda()}")

# Set memory growth for GPU if available
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("Memory growth set for GPU")
    except RuntimeError as e:
        print(e)

TensorFlow version: 2.18.0
GPU available: []
Built with CUDA: False


In [5]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


## 2. Creating Tensors

Tensors are the fundamental data structure in TensorFlow. They are multi-dimensional arrays with a uniform type (dtype). Let's explore different ways to create tensors:

### 2.1 Scalar Tensors (0-D)

In [6]:
# Scalar tensors (rank-0 tensors)
scalar_int = tf.constant(42)
scalar_float = tf.constant(3.14159, dtype=tf.float32)
scalar_string = tf.constant("Hello TensorFlow!")

print("Scalar tensors:")
print(f"Integer: {scalar_int}, shape: {scalar_int.shape}, dtype: {scalar_int.dtype}")
print(f"Float: {scalar_float}, shape: {scalar_float.shape}, dtype: {scalar_float.dtype}")
print(f"String: {scalar_string}, shape: {scalar_string.shape}, dtype: {scalar_string.dtype}")
print(f"Rank (ndim): {tf.rank(scalar_int)}")

Scalar tensors:
Integer: 42, shape: (), dtype: <dtype: 'int32'>
Float: 3.141590118408203, shape: (), dtype: <dtype: 'float32'>
String: b'Hello TensorFlow!', shape: (), dtype: <dtype: 'string'>
Rank (ndim): 0


In [7]:
tensor_one_d = tf.constant([1, 2, 3, 4])
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


### 2.2 Vector Tensors (1-D)

In [8]:
# Vector tensors (rank-1 tensors)
vector_int = tf.constant([1, 2, 3, 4, 5])
vector_float = tf.constant([1.0, 2.5, 3.7, 4.2], dtype=tf.float32)

print("Vector tensors:")
print(f"Integer vector: {vector_int}")
print(f"Shape: {vector_int.shape}, Rank: {tf.rank(vector_int)}, Size: {tf.size(vector_int)}")
print(f"Float vector: {vector_float}")
print(f"Shape: {vector_float.shape}, dtype: {vector_float.dtype}")

# Access elements
print(f"First element: {vector_int[0]}")
print(f"Last element: {vector_int[-1]}")
print(f"Slice [1:4]: {vector_int[1:4]}")

Vector tensors:
Integer vector: [1 2 3 4 5]
Shape: (5,), Rank: 1, Size: 5
Float vector: [1.  2.5 3.7 4.2]
Shape: (4,), dtype: <dtype: 'float32'>
First element: 1
Last element: 5
Slice [1:4]: [2 3 4]


In [9]:
tensor_two_d = tf.constant([[1, 2], [3, 4]])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### 2.3 Matrix Tensors (2-D)

In [10]:
# Matrix tensors (rank-2 tensors)
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
identity_matrix = tf.eye(3)  # 3x3 identity matrix
ones_matrix = tf.ones((2, 4))  # 2x4 matrix of ones
zeros_matrix = tf.zeros((3, 3))  # 3x3 matrix of zeros

print("Matrix tensors:")
print(f"3x3 matrix:\n{matrix}")
print(f"Shape: {matrix.shape}, Rank: {tf.rank(matrix)}")
print(f"\nIdentity matrix:\n{identity_matrix}")
print(f"\nOnes matrix:\n{ones_matrix}")
print(f"\nZeros matrix:\n{zeros_matrix}")

# Matrix indexing
print(f"\nElement at [1,2]: {matrix[1, 2]}")
print(f"Row 1: {matrix[1, :]}")
print(f"Column 2: {matrix[:, 2]}")
print(f"2x2 submatrix:\n{matrix[:2, :2]}")

Matrix tensors:
3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3), Rank: 2

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ones matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Element at [1,2]: 6
Row 1: [4 5 6]
Column 2: [3 6 9]
2x2 submatrix:
[[1 2]
 [4 5]]


In [11]:
tensor_three_d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


### 2.4 Higher-Dimensional Tensors

In [12]:
# 3D tensors (commonly used for RGB images: height x width x channels)
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:")
print(f"Shape: {tensor_3d.shape}, Rank: {tf.rank(tensor_3d)}")
print(f"Tensor:\n{tensor_3d}")

# Random tensors for higher dimensions
random_4d = tf.random.normal((2, 3, 4, 5))  # Batch x Height x Width x Channels
print(f"\n4D Random tensor shape: {random_4d.shape}")

# Useful tensor creation functions
range_tensor = tf.range(10)
linspace_tensor = tf.linspace(0.0, 1.0, 10)
random_uniform = tf.random.uniform((3, 3), minval=0, maxval=10)

print(f"\nRange tensor: {range_tensor}")
print(f"Linspace tensor: {linspace_tensor}")
print(f"Random uniform tensor:\n{random_uniform}")

3D Tensor:
Shape: (2, 2, 2), Rank: 3
Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4D Random tensor shape: (2, 3, 4, 5)

Range tensor: [0 1 2 3 4 5 6 7 8 9]
Linspace tensor: [0.         0.11111111 0.22222222 0.33333334 0.44444445 0.5555556
 0.6666667  0.7777778  0.8888889  1.        ]
Random uniform tensor:
[[1.1037648 4.7701526 9.451875 ]
 [5.5748177 1.8365633 5.6248055]
 [6.8161583 4.641049  5.171734 ]]


In [13]:
tensor_four_d = tf.constant([[[[1, 2, 7], [3, 4, 8]], [[5, 6, 9], [7, 8, 10]]], [[[9, 10, 11], [11, 12, 12]], [[13, 14, 13], [15, 16, 14]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  7]
   [ 3  4  8]]

  [[ 5  6  9]
   [ 7  8 10]]]


 [[[ 9 10 11]
   [11 12 12]]

  [[13 14 13]
   [15 16 14]]]], shape=(2, 2, 2, 3), dtype=int32)


In [14]:
import numpy as np
numpy_array = np.array([1, 2, 3, 4])

## 3. NumPy Interoperability

TensorFlow tensors can be easily converted to/from NumPy arrays, making it seamless to work with existing NumPy-based code.

In [15]:
converted_tensor = tf.constant(numpy_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [16]:
# Convert NumPy array to TensorFlow tensor
numpy_array_2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
tensor_from_numpy = tf.constant(numpy_array_2d)

print("NumPy to TensorFlow conversion:")
print(f"NumPy array:\n{numpy_array_2d}")
print(f"TensorFlow tensor:\n{tensor_from_numpy}")
print(f"Tensor dtype: {tensor_from_numpy.dtype}")

# Convert TensorFlow tensor to NumPy array
tensor_to_convert = tf.constant([[10, 20, 30], [40, 50, 60]], dtype=tf.float32)  # Same shape as numpy_array_2d
numpy_from_tensor = tensor_to_convert.numpy()

print(f"\nTensorFlow to NumPy conversion:")
print(f"TensorFlow tensor:\n{tensor_to_convert}")
print(f"TensorFlow tensor dtype: {tensor_to_convert.dtype}")
print(f"TensorFlow tensor shape: {tensor_to_convert.shape}")
print(f"NumPy array:\n{numpy_from_tensor}")
print(f"NumPy array type: {type(numpy_from_tensor)}")

# Demonstrate that operations work seamlessly (both tensors now have same dtype and shape)
result = tf.add(tensor_from_numpy, tensor_to_convert)
print(f"\nTensor addition result:\n{result}")
print(f"Result dtype: {result.dtype}")
print(f"Result shape: {result.shape}")

NumPy to TensorFlow conversion:
NumPy array:
[[1. 2. 3.]
 [4. 5. 6.]]
TensorFlow tensor:
[[1. 2. 3.]
 [4. 5. 6.]]
Tensor dtype: <dtype: 'float32'>

TensorFlow to NumPy conversion:
TensorFlow tensor:
[[10. 20. 30.]
 [40. 50. 60.]]
TensorFlow tensor dtype: <dtype: 'float32'>
TensorFlow tensor shape: (2, 3)
NumPy array:
[[10. 20. 30.]
 [40. 50. 60.]]
NumPy array type: <class 'numpy.ndarray'>

Tensor addition result:
[[11. 22. 33.]
 [44. 55. 66.]]
Result dtype: <dtype: 'float32'>
Result shape: (2, 3)


## 4. Variables vs Constants

In TensorFlow, there are two main ways to store data:
- **Constants**: Immutable tensors whose values cannot be changed
- **Variables**: Mutable tensors that can be modified during training

In [17]:
# Constants - immutable
constant_tensor = tf.constant([1, 2, 3, 4])
print(f"Constant tensor: {constant_tensor}")

# Variables - mutable (used for model parameters like weights and biases)
variable_tensor = tf.Variable([1.0, 2.0, 3.0, 4.0], name="my_variable")
print(f"Variable tensor: {variable_tensor}")
print(f"Variable name: {variable_tensor.name}")
print(f"Variable trainable: {variable_tensor.trainable}")

# Modify variable values
print("\nModifying variable:")
variable_tensor.assign([10.0, 20.0, 30.0, 40.0])
print(f"After assign: {variable_tensor}")

# Add to variable
variable_tensor.assign_add([1.0, 1.0, 1.0, 1.0])
print(f"After assign_add: {variable_tensor}")

# Subtract from variable
variable_tensor.assign_sub([5.0, 5.0, 5.0, 5.0])
print(f"After assign_sub: {variable_tensor}")

# Initialize variables with different strategies
zeros_var = tf.Variable(tf.zeros((2, 3)))
ones_var = tf.Variable(tf.ones((2, 3)))
random_var = tf.Variable(tf.random.normal((2, 3)))

print(f"\nZeros variable:\n{zeros_var}")
print(f"Ones variable:\n{ones_var}")
print(f"Random variable:\n{random_var}")

Constant tensor: [1 2 3 4]
Variable tensor: <tf.Variable 'my_variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>
Variable name: my_variable:0
Variable trainable: True

Modifying variable:
After assign: <tf.Variable 'my_variable:0' shape=(4,) dtype=float32, numpy=array([10., 20., 30., 40.], dtype=float32)>
After assign_add: <tf.Variable 'my_variable:0' shape=(4,) dtype=float32, numpy=array([11., 21., 31., 41.], dtype=float32)>
After assign_sub: <tf.Variable 'my_variable:0' shape=(4,) dtype=float32, numpy=array([ 6., 16., 26., 36.], dtype=float32)>

Zeros variable:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
Ones variable:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
Random variable:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.7341732 ,  0.74133927, -0.70677614],
       [-0.529937

## 5. Basic Mathematical Operations

TensorFlow provides comprehensive mathematical operations for tensors. These operations are element-wise by default and support broadcasting.

### 5.1 Arithmetic Operations

In [18]:
# Create sample tensors for operations
a = tf.constant([1.0, 2.0, 3.0, 4.0])
b = tf.constant([5.0, 6.0, 7.0, 8.0])
scalar = tf.constant(2.0)

print("Basic arithmetic operations:")
print(f"a = {a}")
print(f"b = {b}")
print(f"scalar = {scalar}")

# Addition
addition = tf.add(a, b)  # or a + b
print(f"\nAddition (a + b): {addition}")
print(f"Scalar addition (a + scalar): {a + scalar}")

# Subtraction
subtraction = tf.subtract(b, a)  # or b - a
print(f"Subtraction (b - a): {subtraction}")

# Multiplication
multiplication = tf.multiply(a, b)  # or a * b (element-wise)
print(f"Multiplication (a * b): {multiplication}")

# Division
division = tf.divide(b, a)  # or b / a
print(f"Division (b / a): {division}")

# Power
power = tf.pow(a, 2)  # or a ** 2
print(f"Power (a^2): {power}")

# Square root
sqrt_a = tf.sqrt(a)
print(f"Square root of a: {sqrt_a}")

# Absolute value
negative_tensor = tf.constant([-1.0, -2.0, 3.0, -4.0])
abs_value = tf.abs(negative_tensor)
print(f"Absolute value of {negative_tensor}: {abs_value}")

Basic arithmetic operations:
a = [1. 2. 3. 4.]
b = [5. 6. 7. 8.]
scalar = 2.0

Addition (a + b): [ 6.  8. 10. 12.]
Scalar addition (a + scalar): [3. 4. 5. 6.]
Subtraction (b - a): [4. 4. 4. 4.]
Multiplication (a * b): [ 5. 12. 21. 32.]
Division (b / a): [5.        3.        2.3333333 2.       ]
Power (a^2): [ 1.  4.  9. 16.]
Square root of a: [1.        1.4142135 1.7320508 2.       ]
Absolute value of [-1. -2.  3. -4.]: [1. 2. 3. 4.]


### 5.2 Reduction Operations

Reduction operations compute a single value from a tensor by applying an operation across specified dimensions.

In [19]:
# Create a 2D tensor for reduction operations
matrix_2d = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
print(f"2D Matrix:\n{matrix_2d}")

# Sum operations
total_sum = tf.reduce_sum(matrix_2d)
sum_axis_0 = tf.reduce_sum(matrix_2d, axis=0)  # Sum across rows
sum_axis_1 = tf.reduce_sum(matrix_2d, axis=1)  # Sum across columns

print(f"\nReduction operations:")
print(f"Total sum: {total_sum}")
print(f"Sum across rows (axis=0): {sum_axis_0}")
print(f"Sum across columns (axis=1): {sum_axis_1}")

# Mean operations
total_mean = tf.reduce_mean(matrix_2d)
mean_axis_0 = tf.reduce_mean(matrix_2d, axis=0)
mean_axis_1 = tf.reduce_mean(matrix_2d, axis=1)

print(f"\nMean operations:")
print(f"Total mean: {total_mean}")
print(f"Mean across rows (axis=0): {mean_axis_0}")
print(f"Mean across columns (axis=1): {mean_axis_1}")

# Min and Max operations
maximum = tf.reduce_max(matrix_2d)
minimum = tf.reduce_min(matrix_2d)
max_axis_1 = tf.reduce_max(matrix_2d, axis=1)

print(f"\nMin/Max operations:")
print(f"Maximum: {maximum}")
print(f"Minimum: {minimum}")
print(f"Max across columns (axis=1): {max_axis_1}")

# Standard deviation and variance
std_dev = tf.math.reduce_std(matrix_2d)
variance = tf.math.reduce_variance(matrix_2d)

print(f"\nStatistical operations:")
print(f"Standard deviation: {std_dev}")
print(f"Variance: {variance}")

2D Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Reduction operations:
Total sum: 45.0
Sum across rows (axis=0): [12. 15. 18.]
Sum across columns (axis=1): [ 6. 15. 24.]

Mean operations:
Total mean: 5.0
Mean across rows (axis=0): [4. 5. 6.]
Mean across columns (axis=1): [2. 5. 8.]

Min/Max operations:
Maximum: 9.0
Minimum: 1.0
Max across columns (axis=1): [3. 6. 9.]

Statistical operations:
Standard deviation: 2.58198881149292
Variance: 6.666666507720947


### 5.3 Trigonometric and Logarithmic Functions

In [20]:
# Trigonometric functions
angles = tf.constant([0.0, np.pi/4, np.pi/2, np.pi])  # Use numpy values directly
print(f"Angles: {angles}")

sin_values = tf.sin(angles)
cos_values = tf.cos(angles)
tan_values = tf.tan(angles)

print(f"\nTrigonometric functions:")
print(f"sin(angles): {sin_values}")
print(f"cos(angles): {cos_values}")
print(f"tan(angles): {tan_values}")

# Logarithmic and exponential functions
positive_values = tf.constant([1.0, 2.0, 10.0, 100.0])
print(f"\nPositive values: {positive_values}")

log_natural = tf.math.log(positive_values)  # Natural logarithm
log_10 = tf.math.log(positive_values) / tf.math.log(10.0)  # Log base 10
exp_values = tf.exp(positive_values)  # Exponential

print(f"Natural log: {log_natural}")
print(f"Log base 10: {log_10}")
print(f"Exponential: {exp_values}")

# Hyperbolic functions
values = tf.constant([-1.0, 0.0, 1.0, 2.0])
sinh_values = tf.sinh(values)
cosh_values = tf.cosh(values)
tanh_values = tf.tanh(values)

print(f"\nHyperbolic functions for {values}:")
print(f"sinh: {sinh_values}")
print(f"cosh: {cosh_values}")
print(f"tanh: {tanh_values}")

Angles: [0.        0.7853982 1.5707964 3.1415927]

Trigonometric functions:
sin(angles): [ 0.0000000e+00  7.0710677e-01  1.0000000e+00 -8.7422777e-08]
cos(angles): [ 1.0000000e+00  7.0710677e-01 -4.3711388e-08 -1.0000000e+00]
tan(angles): [ 0.0000000e+00  1.0000000e+00 -2.2877332e+07  8.7422777e-08]

Positive values: [  1.   2.  10. 100.]
Natural log: [0.        0.6931472 2.3025851 4.6051702]
Log base 10: [0.         0.30102998 1.         2.        ]
Exponential: [2.7182817e+00 7.3890562e+00 2.2026465e+04           inf]

Hyperbolic functions for [-1.  0.  1.  2.]:
sinh: [-1.1752012  0.         1.1752012  3.6268604]
cosh: [1.5430807 1.        1.5430807 3.7621956]
tanh: [-0.7615942  0.         0.7615942  0.9640276]


## 6. Linear Algebra Operations

Linear algebra is fundamental to deep learning. TensorFlow provides comprehensive support for matrix operations.

### 6.1 Matrix Multiplication

In [21]:
# Matrix multiplication examples
A = tf.constant([[1.0, 2.0], [3.0, 4.0]])
B = tf.constant([[5.0, 6.0], [7.0, 8.0]])
vector = tf.constant([[1.0], [2.0]])

print("Matrix multiplication:")
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")
print(f"Vector:\n{vector}")

# Matrix multiplication using tf.matmul
AB = tf.matmul(A, B)
print(f"\nA @ B (matrix multiplication):\n{AB}")

# Matrix-vector multiplication
Av = tf.matmul(A, vector)
print(f"\nA @ vector:\n{Av}")

# Transpose
A_transpose = tf.transpose(A)
print(f"\nTranspose of A:\n{A_transpose}")

# Batch matrix multiplication
batch_A = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
batch_B = tf.constant([[[1.0, 0.0], [0.0, 1.0]], [[2.0, 1.0], [1.0, 2.0]]])
batch_result = tf.matmul(batch_A, batch_B)
print(f"\nBatch matrix multiplication result:\n{batch_result}")

# Element-wise multiplication (Hadamard product)
hadamard = tf.multiply(A, B)  # or A * B
print(f"\nHadamard product (A * B):\n{hadamard}")

Matrix multiplication:
Matrix A:
[[1. 2.]
 [3. 4.]]
Matrix B:
[[5. 6.]
 [7. 8.]]
Vector:
[[1.]
 [2.]]

A @ B (matrix multiplication):
[[19. 22.]
 [43. 50.]]

A @ vector:
[[ 5.]
 [11.]]

Transpose of A:
[[1. 3.]
 [2. 4.]]

Batch matrix multiplication result:
[[[ 1.  2.]
  [ 3.  4.]]

 [[16. 17.]
  [22. 23.]]]

Hadamard product (A * B):
[[ 5. 12.]
 [21. 32.]]


### 6.2 Advanced Linear Algebra Operations

In [22]:
# Create matrices for advanced operations
square_matrix = tf.constant([[4.0, 2.0], [1.0, 3.0]], dtype=tf.float32)
print(f"Square matrix:\n{square_matrix}")

# Determinant
det = tf.linalg.det(square_matrix)
print(f"\nDeterminant: {det}")

# Matrix inverse
try:
    inverse = tf.linalg.inv(square_matrix)
    print(f"Matrix inverse:\n{inverse}")
    
    # Verify inverse (should be identity matrix)
    verification = tf.matmul(square_matrix, inverse)
    print(f"A @ A^(-1) (should be identity):\n{verification}")
except:
    print("Matrix is not invertible")

# Eigenvalues and eigenvectors
symmetric_matrix = tf.constant([[3.0, 1.0], [1.0, 3.0]], dtype=tf.float32)
eigenvalues, eigenvectors = tf.linalg.eigh(symmetric_matrix)
print(f"\nSymmetric matrix:\n{symmetric_matrix}")
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

# Singular Value Decomposition (SVD)
matrix_for_svd = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=tf.float32)
s, u, v = tf.linalg.svd(matrix_for_svd)
print(f"\nMatrix for SVD:\n{matrix_for_svd}")
print(f"Singular values: {s}")
print(f"U matrix shape: {u.shape}")
print(f"V matrix shape: {v.shape}")

# QR decomposition
q, r = tf.linalg.qr(tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=tf.float32))
print(f"\nQR decomposition:")
print(f"Q matrix:\n{q}")
print(f"R matrix:\n{r}")

Square matrix:
[[4. 2.]
 [1. 3.]]

Determinant: 10.0
Matrix inverse:
[[ 0.3 -0.2]
 [-0.1  0.4]]
A @ A^(-1) (should be identity):
[[1. 0.]
 [0. 1.]]

Symmetric matrix:
[[3. 1.]
 [1. 3.]]
Eigenvalues: [1.9999998 3.9999998]
Eigenvectors:
[[-0.7071067   0.70710677]
 [ 0.70710677  0.7071067 ]]

Matrix for SVD:
[[1. 2. 3.]
 [4. 5. 6.]]
Singular values: [9.508034   0.77286935]
U matrix shape: (2, 2)
V matrix shape: (3, 2)

QR decomposition:
Q matrix:
[[-0.16903079  0.897085  ]
 [-0.5070925   0.2760267 ]
 [-0.8451542  -0.34503305]]
R matrix:
[[-5.91608    -7.437357  ]
 [ 0.          0.82807845]]


## 7. Tensor Manipulation and Reshaping

Understanding how to manipulate tensor shapes is crucial for deep learning operations.

### 7.1 Reshaping Operations

In [23]:
# Original tensor
original = tf.range(12, dtype=tf.float32)
print(f"Original tensor: {original}")
print(f"Shape: {original.shape}")

# Reshape to different dimensions
reshaped_2d = tf.reshape(original, (3, 4))
reshaped_3d = tf.reshape(original, (2, 2, 3))
reshaped_4d = tf.reshape(original, (1, 2, 2, 3))

print(f"\nReshape to (3, 4):\n{reshaped_2d}")
print(f"Shape: {reshaped_2d.shape}")

print(f"\nReshape to (2, 2, 3):\n{reshaped_3d}")
print(f"Shape: {reshaped_3d.shape}")

print(f"\nReshape to (1, 2, 2, 3):\n{reshaped_4d}")
print(f"Shape: {reshaped_4d.shape}")

# Flatten tensor
flattened = tf.reshape(reshaped_3d, (-1,))  # -1 means "infer this dimension"
print(f"\nFlattened tensor: {flattened}")
print(f"Shape: {flattened.shape}")

# Expand dimensions
expanded = tf.expand_dims(original, axis=0)  # Add dimension at axis 0
expanded_end = tf.expand_dims(original, axis=-1)  # Add dimension at end

print(f"\nExpand dims at axis 0: {expanded}")
print(f"Shape: {expanded.shape}")
print(f"\nExpand dims at axis -1: {expanded_end}")
print(f"Shape: {expanded_end.shape}")

# Squeeze dimensions (remove size-1 dimensions)
to_squeeze = tf.constant([[[1], [2], [3], [4]]])
squeezed = tf.squeeze(to_squeeze)
print(f"\nOriginal with size-1 dims: {to_squeeze}, shape: {to_squeeze.shape}")
print(f"After squeeze: {squeezed}, shape: {squeezed.shape}")

Original tensor: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
Shape: (12,)

Reshape to (3, 4):
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Shape: (3, 4)

Reshape to (2, 2, 3):
[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
Shape: (2, 2, 3)

Reshape to (1, 2, 2, 3):
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]]

  [[ 6.  7.  8.]
   [ 9. 10. 11.]]]]
Shape: (1, 2, 2, 3)

Flattened tensor: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
Shape: (12,)

Expand dims at axis 0: [[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]]
Shape: (1, 12)

Expand dims at axis -1: [[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]]
Shape: (12, 1)

Original with size-1 dims: [[[1]
  [2]
  [3]
  [4]]], shape: (1, 4, 1)
After squeeze: [1 2 3 4], shape: (4,)


### 7.2 Concatenation and Splitting

In [24]:
# Create tensors for concatenation
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])
tensor3 = tf.constant([[9, 10], [11, 12]])

print(f"Tensor 1:\n{tensor1}")
print(f"Tensor 2:\n{tensor2}")
print(f"Tensor 3:\n{tensor3}")

# Concatenate along different axes
concat_axis_0 = tf.concat([tensor1, tensor2, tensor3], axis=0)  # Stack vertically
concat_axis_1 = tf.concat([tensor1, tensor2, tensor3], axis=1)  # Stack horizontally

print(f"\nConcatenate along axis 0 (vertical):\n{concat_axis_0}")
print(f"Shape: {concat_axis_0.shape}")

print(f"\nConcatenate along axis 1 (horizontal):\n{concat_axis_1}")
print(f"Shape: {concat_axis_1.shape}")

# Stack tensors (creates new dimension)
stacked = tf.stack([tensor1, tensor2, tensor3], axis=0)
print(f"\nStacked tensors (new dimension):\n{stacked}")
print(f"Shape: {stacked.shape}")

# Split tensors
large_tensor = tf.constant([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(f"\nLarge tensor to split:\n{large_tensor}")

# Split into equal parts
split_result = tf.split(large_tensor, num_or_size_splits=3, axis=1)
print(f"Split into 3 parts along axis 1:")
for i, part in enumerate(split_result):
    print(f"Part {i}: {part}")

# Unstack (inverse of stack)
unstacked = tf.unstack(stacked, axis=0)
print(f"\nUnstacked tensors:")
for i, tensor in enumerate(unstacked):
    print(f"Tensor {i}:\n{tensor}")

Tensor 1:
[[1 2]
 [3 4]]
Tensor 2:
[[5 6]
 [7 8]]
Tensor 3:
[[ 9 10]
 [11 12]]

Concatenate along axis 0 (vertical):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape: (6, 2)

Concatenate along axis 1 (horizontal):
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
Shape: (2, 6)

Stacked tensors (new dimension):
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape: (3, 2, 2)

Large tensor to split:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Split into 3 parts along axis 1:
Part 0: [[1 2]
 [7 8]]
Part 1: [[ 3  4]
 [ 9 10]]
Part 2: [[ 5  6]
 [11 12]]

Unstacked tensors:
Tensor 0:
[[1 2]
 [3 4]]
Tensor 1:
[[5 6]
 [7 8]]
Tensor 2:
[[ 9 10]
 [11 12]]


## 8. Broadcasting

Broadcasting allows operations between tensors of different shapes by automatically expanding the smaller tensor to match the larger one's shape.

In [25]:
# Broadcasting examples
matrix = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
scalar = tf.constant(10.0)
vector_row = tf.constant([1.0, 2.0, 3.0])  # Shape: (3,)
vector_col = tf.constant([[1.0], [2.0]])    # Shape: (2, 1)

print(f"Matrix shape: {matrix.shape}")
print(f"Matrix:\n{matrix}")
print(f"\nScalar: {scalar}")
print(f"Vector (row): {vector_row}")
print(f"Vector (column):\n{vector_col}")

# Scalar broadcasting
scalar_broadcast = matrix + scalar
print(f"\nMatrix + Scalar (broadcasting):\n{scalar_broadcast}")

# Vector broadcasting (row)
vector_broadcast_row = matrix + vector_row
print(f"\nMatrix + Row Vector (broadcasting):\n{vector_broadcast_row}")

# Vector broadcasting (column)
vector_broadcast_col = matrix + vector_col
print(f"\nMatrix + Column Vector (broadcasting):\n{vector_broadcast_col}")

# More complex broadcasting
tensor_3d = tf.random.normal((2, 3, 4))
vector_for_3d = tf.constant([1.0, 2.0, 3.0, 4.0])  # Shape: (4,)

print(f"\n3D tensor shape: {tensor_3d.shape}")
print(f"Vector shape: {vector_for_3d.shape}")

broadcast_result = tensor_3d + vector_for_3d
print(f"Broadcast result shape: {broadcast_result.shape}")

# Manual broadcasting using tf.broadcast_to
manual_broadcast = tf.broadcast_to(vector_row, (2, 3))
print(f"\nManual broadcast of {vector_row} to shape (2, 3):\n{manual_broadcast}")

# Check if two tensors are broadcast compatible
try:
    broadcast_shapes = tf.broadcast_dynamic_shape(tf.shape(matrix), tf.shape(vector_row))
    print(f"\nBroadcast compatible shapes result: {broadcast_shapes}")
except:
    print("Shapes are not broadcast compatible")

Matrix shape: (2, 3)
Matrix:
[[1. 2. 3.]
 [4. 5. 6.]]

Scalar: 10.0
Vector (row): [1. 2. 3.]
Vector (column):
[[1.]
 [2.]]

Matrix + Scalar (broadcasting):
[[11. 12. 13.]
 [14. 15. 16.]]

Matrix + Row Vector (broadcasting):
[[2. 4. 6.]
 [5. 7. 9.]]

Matrix + Column Vector (broadcasting):
[[2. 3. 4.]
 [6. 7. 8.]]

3D tensor shape: (2, 3, 4)
Vector shape: (4,)
Broadcast result shape: (2, 3, 4)

Manual broadcast of [1. 2. 3.] to shape (2, 3):
[[1. 2. 3.]
 [1. 2. 3.]]

Broadcast compatible shapes result: [2 3]


## 9. Activation Functions

Activation functions are crucial components in neural networks. TensorFlow provides many common activation functions.

In [26]:
# Create input values for activation functions
x = tf.linspace(-5.0, 5.0, 11)
print(f"Input values: {x}")

# Common activation functions
sigmoid_output = tf.nn.sigmoid(x)
tanh_output = tf.nn.tanh(x)
relu_output = tf.nn.relu(x)
leaky_relu_output = tf.nn.leaky_relu(x, alpha=0.2)
elu_output = tf.nn.elu(x)
swish_output = tf.nn.swish(x)

print(f"\nActivation function outputs:")
print(f"Sigmoid: {sigmoid_output}")
print(f"Tanh: {tanh_output}")
print(f"ReLU: {relu_output}")
print(f"Leaky ReLU: {leaky_relu_output}")
print(f"ELU: {elu_output}")
print(f"Swish: {swish_output}")

# Softmax activation (commonly used for classification)
logits = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
softmax_output = tf.nn.softmax(logits)
print(f"\nLogits: {logits}")
print(f"Softmax output: {softmax_output}")
print(f"Softmax sum per row: {tf.reduce_sum(softmax_output, axis=1)}")

# Log softmax (numerically stable)
log_softmax_output = tf.nn.log_softmax(logits)
print(f"Log softmax output: {log_softmax_output}")

# Gelu activation (used in transformers)
gelu_output = tf.nn.gelu(x)
print(f"GELU output: {gelu_output}")

# Custom activation function using mathematical operations
def custom_activation(x):
    """Custom activation: x * sigmoid(x)"""
    return x * tf.nn.sigmoid(x)

custom_output = custom_activation(x)
print(f"Custom activation (x * sigmoid(x)): {custom_output}")

Input values: [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]

Activation function outputs:
Sigmoid: [0.00669285 0.01798621 0.04742587 0.11920294 0.2689414  0.5
 0.73105854 0.8807971  0.95257413 0.98201376 0.9933072 ]
Tanh: [-0.99990916 -0.9993292  -0.9950547  -0.9640276  -0.7615942   0.
  0.7615942   0.9640276   0.9950547   0.9993292   0.99990916]
ReLU: [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5.]
Leaky ReLU: [-1.  -0.8 -0.6 -0.4 -0.2  0.   1.   2.   3.   4.   5. ]
ELU: [-0.99326205 -0.9816844  -0.95021296 -0.86466473 -0.63212055  0.
  1.          2.          3.          4.          5.        ]
Swish: [-0.03346426 -0.07194484 -0.1422776  -0.23840588 -0.2689414   0.
  0.73105854  1.7615942   2.8577223   3.928055    4.966536  ]

Logits: [[1. 2. 3.]
 [4. 5. 6.]]
Softmax output: [[0.09003057 0.24472848 0.6652409 ]
 [0.09003057 0.24472848 0.6652409 ]]
Softmax sum per row: [0.99999994 0.99999994]
Log softmax output: [[-2.407606   -1.4076059  -0.40760595]
 [-2.407606   -1.4076059  -0.40760595]]
GELU out

## 10. Loss Functions

Loss functions measure how well a model's predictions match the true values. They are essential for training neural networks.

In [27]:
# Regression loss functions
y_true_regression = tf.constant([1.0, 2.0, 3.0, 4.0])
y_pred_regression = tf.constant([1.1, 2.2, 2.9, 3.8])

print("Regression Loss Functions:")
print(f"True values: {y_true_regression}")
print(f"Predicted values: {y_pred_regression}")

# Mean Squared Error (MSE)
mse = tf.reduce_mean(tf.square(y_true_regression - y_pred_regression))
print(f"MSE: {mse}")

# Mean Absolute Error (MAE)  
mae = tf.reduce_mean(tf.abs(y_true_regression - y_pred_regression))
print(f"MAE: {mae}")

# Huber Loss (robust to outliers)
huber_loss_fn = tf.keras.losses.Huber()
huber = huber_loss_fn(y_true_regression, y_pred_regression)
print(f"Huber Loss: {huber}")

# Classification loss functions
y_true_class = tf.constant([0, 1, 2, 1])  # Class indices
y_pred_logits = tf.constant([[2.0, 0.5, 0.1],   # Logits for class 0
                             [0.1, 2.0, 0.3],   # Logits for class 1
                             [0.2, 0.1, 1.8],   # Logits for class 2
                             [0.3, 1.5, 0.2]])  # Logits for class 1

print(f"\nClassification Loss Functions:")
print(f"True classes: {y_true_class}")
print(f"Predicted logits:\n{y_pred_logits}")

# Sparse categorical crossentropy (for integer labels)
sparse_ce_loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
sparse_ce = sparse_ce_loss_fn(y_true_class, y_pred_logits)
print(f"Sparse Categorical Crossentropy: {sparse_ce}")

# Convert to one-hot for categorical crossentropy
y_true_onehot = tf.one_hot(y_true_class, depth=3)
categorical_ce_loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits=True)
categorical_ce = categorical_ce_loss_fn(y_true_onehot, y_pred_logits)
print(f"Categorical Crossentropy: {categorical_ce}")

# Binary classification
y_true_binary = tf.constant([0.0, 1.0, 1.0, 0.0])
y_pred_binary = tf.constant([0.1, 0.9, 0.8, 0.2])

binary_ce_loss_fn = tf.keras.losses.BinaryCrossentropy()
binary_ce = binary_ce_loss_fn(y_true_binary, y_pred_binary)
print(f"\nBinary Crossentropy: {binary_ce}")

# Custom loss function
def custom_loss(y_true, y_pred):
    """Custom loss: weighted MSE"""
    weights = tf.constant([1.0, 2.0, 1.5, 0.5])
    squared_diff = tf.square(y_true - y_pred)
    weighted_squared_diff = weights * squared_diff
    return tf.reduce_mean(weighted_squared_diff)

custom = custom_loss(y_true_regression, y_pred_regression)
print(f"\nCustom weighted MSE: {custom}")

Regression Loss Functions:
True values: [1. 2. 3. 4.]
Predicted values: [1.1 2.2 2.9 3.8]
MSE: 0.025000005960464478
MAE: 0.15000000596046448
Huber Loss: 0.012500002980232239

Classification Loss Functions:
True classes: [0 1 2 1]
Predicted logits:
[[2.  0.5 0.1]
 [0.1 2.  0.3]
 [0.2 0.1 1.8]
 [0.3 1.5 0.2]]
Sparse Categorical Crossentropy: 0.3456231355667114
Categorical Crossentropy: 0.3456231355667114

Binary Crossentropy: 0.16425204277038574

Custom weighted MSE: 0.0312500037252903


## 11. Gradient Computation and Automatic Differentiation

TensorFlow's automatic differentiation (autodiff) is fundamental for training neural networks. It allows us to compute gradients automatically.

In [28]:
# Simple gradient computation
x = tf.Variable(3.0)

# Record operations for gradient computation
with tf.GradientTape() as tape:
    y = x ** 2 + 2 * x + 1

# Compute gradient dy/dx
gradient = tape.gradient(y, x)
print(f"x = {x.numpy()}")
print(f"y = x^2 + 2x + 1 = {y.numpy()}")
print(f"dy/dx = 2x + 2 = {gradient.numpy()}")

# Multiple variables
x1 = tf.Variable(2.0)
x2 = tf.Variable(3.0)

with tf.GradientTape() as tape:
    z = x1**2 + x2**3 + 2*x1*x2

# Compute gradients with respect to both variables
gradients = tape.gradient(z, [x1, x2])
print(f"\nMultiple variables:")
print(f"x1 = {x1.numpy()}, x2 = {x2.numpy()}")
print(f"z = x1^2 + x2^3 + 2*x1*x2 = {z.numpy()}")
print(f"dz/dx1 = {gradients[0].numpy()}")
print(f"dz/dx2 = {gradients[1].numpy()}")

# Gradient of a vector function
x_vec = tf.Variable([1.0, 2.0, 3.0])

with tf.GradientTape() as tape:
    y_vec = tf.reduce_sum(x_vec**2)

grad_vec = tape.gradient(y_vec, x_vec)
print(f"\nVector function:")
print(f"x = {x_vec.numpy()}")
print(f"y = sum(x^2) = {y_vec.numpy()}")
print(f"dy/dx = {grad_vec.numpy()}")

# Higher-order gradients
x = tf.Variable(2.0)

with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y = x**4
    first_grad = tape1.gradient(y, x)  # First derivative
second_grad = tape2.gradient(first_grad, x)  # Second derivative

print(f"\nHigher-order gradients:")
print(f"x = {x.numpy()}")
print(f"y = x^4 = {y.numpy()}")
print(f"dy/dx = 4x^3 = {first_grad.numpy()}")
print(f"d²y/dx² = 12x^2 = {second_grad.numpy()}")

# Gradient computation with loss function (mini training example)
# Simple linear regression: y = wx + b
w = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.zeros([1]))

# Sample data
x_data = tf.constant([[1.0], [2.0], [3.0], [4.0]])
y_true = tf.constant([[2.0], [4.0], [6.0], [8.0]])  # y = 2x

with tf.GradientTape() as tape:
    y_pred = x_data * w + b
    loss = tf.reduce_mean(tf.square(y_true - y_pred))

# Compute gradients
gradients = tape.gradient(loss, [w, b])
print(f"\nLinear regression gradients:")
print(f"Initial w = {w.numpy()}, b = {b.numpy()}")
print(f"Loss = {loss.numpy()}")
print(f"dL/dw = {gradients[0].numpy()}")
print(f"dL/db = {gradients[1].numpy()}")

x = 3.0
y = x^2 + 2x + 1 = 16.0
dy/dx = 2x + 2 = 8.0

Multiple variables:
x1 = 2.0, x2 = 3.0
z = x1^2 + x2^3 + 2*x1*x2 = 43.0
dz/dx1 = 10.0
dz/dx2 = 31.0

Vector function:
x = [1. 2. 3.]
y = sum(x^2) = 14.0
dy/dx = [2. 4. 6.]

Higher-order gradients:
x = 2.0
y = x^4 = 16.0
dy/dx = 4x^3 = 32.0
d²y/dx² = 12x^2 = 48.0

Linear regression gradients:
Initial w = [-0.98013866], b = [0.]
Loss = 66.60920715332031
dL/dw = [-44.70208]
dL/db = [-14.900694]


## 12. Random Number Generation

TensorFlow provides various functions for generating random numbers, which are essential for initialization and data augmentation.

In [29]:
# Set random seed for reproducibility
tf.random.set_seed(42)

# Normal (Gaussian) distribution
normal_random = tf.random.normal((3, 3), mean=0.0, stddev=1.0)
print(f"Normal random (mean=0, stddev=1):\n{normal_random}")

# Uniform distribution
uniform_random = tf.random.uniform((2, 4), minval=0.0, maxval=1.0)
print(f"\nUniform random [0, 1):\n{uniform_random}")

# Random integers
random_ints = tf.random.uniform((2, 3), minval=1, maxval=10, dtype=tf.int32)
print(f"\nRandom integers [1, 10):\n{random_ints}")

# Truncated normal (values more than 2 std devs are re-drawn)
truncated_normal = tf.random.truncated_normal((2, 3), mean=0.0, stddev=1.0)
print(f"\nTruncated normal:\n{truncated_normal}")

# Random shuffle
sequence = tf.range(10)
shuffled = tf.random.shuffle(sequence)
print(f"\nOriginal sequence: {sequence}")
print(f"Shuffled sequence: {shuffled}")

# Dropout simulation (randomly set elements to zero)
input_tensor = tf.ones((3, 4))
dropout_rate = 0.3
random_mask = tf.random.uniform((3, 4)) > dropout_rate
dropout_output = input_tensor * tf.cast(random_mask, tf.float32)

print(f"\nDropout simulation:")
print(f"Input tensor:\n{input_tensor}")
print(f"Random mask:\n{random_mask}")
print(f"After dropout:\n{dropout_output}")

# Categorical sampling
logits = tf.constant([[1.0, 2.0, 3.0], [1.5, 0.5, 2.0]])
samples = tf.random.categorical(logits, num_samples=5)
print(f"\nCategorical sampling:")
print(f"Logits:\n{logits}")
print(f"Samples (5 per row):\n{samples}")

# Random normal with different parameters
mean_tensor = tf.constant([1.0, 2.0, 3.0])
std_tensor = tf.constant([0.1, 0.5, 1.0])
random_with_params = tf.random.normal((100, 3)) * std_tensor + mean_tensor

print(f"\nRandom normal with different means and stds:")
print(f"Target means: {mean_tensor}")
print(f"Target stds: {std_tensor}")
print(f"Actual means: {tf.reduce_mean(random_with_params, axis=0)}")
print(f"Actual stds: {tf.math.reduce_std(random_with_params, axis=0)}")

# Bernoulli distribution (useful for binary masks)
prob = 0.7
bernoulli_samples = tf.random.uniform((3, 3)) < prob
print(f"\nBernoulli samples (p={prob}):\n{bernoulli_samples}")

Normal random (mean=0, stddev=1):
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]
 [-0.5573232  0.539707   1.6994323]]

Uniform random [0, 1):
[[0.68789124 0.48447883 0.9309944  0.252187  ]
 [0.73115396 0.89256823 0.94674826 0.7493341 ]]

Random integers [1, 10):
[[9 9 8]
 [5 8 4]]

Truncated normal:
[[ 0.65648675 -0.4130517   0.33997506]
 [-1.0056272   1.6890494   1.1180437 ]]

Original sequence: [0 1 2 3 4 5 6 7 8 9]
Shuffled sequence: [9 4 8 1 0 2 7 3 5 6]

Dropout simulation:
Input tensor:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random mask:
[[ True False  True False]
 [ True  True False  True]
 [False  True  True False]]
After dropout:
[[1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 1. 1. 0.]]

Categorical sampling:
Logits:
[[1.  2.  3. ]
 [1.5 0.5 2. ]]
Samples (5 per row):
[[2 2 2 2 2]
 [2 2 1 2 0]]

Random normal with different means and stds:
Target means: [1. 2. 3.]
Target stds: [0.1 0.5 1. ]
Actual means: [0.9859023 1.9779978 3.025094 ]
Actual stds: [0.09437

## 13. Conditional Operations

TensorFlow provides conditional operations that allow you to build dynamic computational graphs.

In [30]:
# tf.where: element-wise conditional selection
condition = tf.constant([True, False, True, False])
x = tf.constant([1, 2, 3, 4])
y = tf.constant([10, 20, 30, 40])

result = tf.where(condition, x, y)
print(f"Condition: {condition}")
print(f"x: {x}")
print(f"y: {y}")
print(f"tf.where result: {result}")

# Numerical condition
values = tf.constant([-2.0, -1.0, 0.0, 1.0, 2.0])
positive_mask = values > 0

# Select positive values, replace negative with zero
filtered = tf.where(positive_mask, values, 0.0)
print(f"\nValues: {values}")
print(f"Positive mask: {positive_mask}")
print(f"Filtered (negatives become 0): {filtered}")

# tf.cond: conditional execution (like if-else)
x = tf.constant(5.0)

def true_fn():
    return tf.square(x)

def false_fn():
    return tf.sqrt(x)

# This will execute true_fn since x > 3
result_cond = tf.cond(x > 3, true_fn, false_fn)
print(f"\nx = {x}")
print(f"tf.cond result (x > 3): {result_cond}")

# tf.case: multiple conditions (like switch statement)
def case_example(x):
    return tf.case([
        (tf.less(x, 0), lambda: tf.constant("negative")),
        (tf.equal(x, 0), lambda: tf.constant("zero")),
        (tf.greater(x, 0), lambda: tf.constant("positive"))
    ], default=lambda: tf.constant("unknown"))

test_values = [-1.0, 0.0, 1.0]
for val in test_values:
    result = case_example(tf.constant(val))
    print(f"case({val}): {result.numpy().decode()}")

# Clipping values (commonly used operation)
values_to_clip = tf.constant([-5.0, -1.0, 0.0, 1.0, 5.0])
clipped = tf.clip_by_value(values_to_clip, -2.0, 2.0)
print(f"\nOriginal values: {values_to_clip}")
print(f"Clipped to [-2, 2]: {clipped}")

# Boolean operations
a = tf.constant([True, True, False, False])
b = tf.constant([True, False, True, False])

logical_and = tf.logical_and(a, b)
logical_or = tf.logical_or(a, b)
logical_not = tf.logical_not(a)

print(f"\nBoolean operations:")
print(f"a: {a}")
print(f"b: {b}")
print(f"a AND b: {logical_and}")
print(f"a OR b: {logical_or}")
print(f"NOT a: {logical_not}")

# Masking and advanced indexing
data = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = tf.constant([True, False, True])

# Select rows based on mask
masked_data = tf.boolean_mask(data, mask)
print(f"\nData:\n{data}")
print(f"Mask: {mask}")
print(f"Masked data:\n{masked_data}")

Condition: [ True False  True False]
x: [1 2 3 4]
y: [10 20 30 40]
tf.where result: [ 1 20  3 40]

Values: [-2. -1.  0.  1.  2.]
Positive mask: [False False False  True  True]
Filtered (negatives become 0): [0. 0. 0. 1. 2.]

x = 5.0
tf.cond result (x > 3): 25.0
case(-1.0): negative
case(0.0): zero
case(1.0): positive

Original values: [-5. -1.  0.  1.  5.]
Clipped to [-2, 2]: [-2. -1.  0.  1.  2.]

Boolean operations:
a: [ True  True False False]
b: [ True False  True False]
a AND b: [ True False False False]
a OR b: [ True  True  True False]
NOT a: [False False  True  True]

Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mask: [ True False  True]
Masked data:
[[1 2 3]
 [7 8 9]]


## 14. Summary and Best Practices

This notebook covered the fundamental mathematical operations and concepts in TensorFlow:

### Key Concepts Covered:
1. **Tensor Creation**: Scalars, vectors, matrices, and higher-dimensional tensors
2. **Variables vs Constants**: Understanding mutable vs immutable tensors
3. **Mathematical Operations**: Arithmetic, reduction, trigonometric, and logarithmic functions
4. **Linear Algebra**: Matrix operations, decompositions, and transformations
5. **Tensor Manipulation**: Reshaping, broadcasting, concatenation, and splitting
6. **Activation Functions**: Common neural network activation functions
7. **Loss Functions**: Regression and classification loss functions
8. **Automatic Differentiation**: Gradient computation for optimization
9. **Random Operations**: Number generation and sampling techniques
10. **Conditional Operations**: Dynamic graph construction with conditions

### Best Practices:
- Always specify data types explicitly when precision matters
- Use broadcasting instead of explicit expansion when possible
- Prefer tf.Variable for trainable parameters and tf.constant for fixed values
- Use tf.GradientTape for custom training loops and gradient computation
- Set random seeds for reproducible experiments
- Use appropriate activation and loss functions for your specific task
- Leverage TensorFlow's automatic differentiation for gradient-based optimization

In [31]:
# Final example: Putting it all together
# Simple neural network forward pass with all the concepts we've learned

# Initialize parameters
input_size = 4
hidden_size = 3
output_size = 2
batch_size = 2

# Random input data (batch_size, input_size)
X = tf.random.normal((batch_size, input_size))

# Initialize weights and biases
W1 = tf.Variable(tf.random.normal((input_size, hidden_size)) * 0.1, name="W1")
b1 = tf.Variable(tf.zeros((hidden_size,)), name="b1")
W2 = tf.Variable(tf.random.normal((hidden_size, output_size)) * 0.1, name="W2")
b2 = tf.Variable(tf.zeros((output_size,)), name="b2")

print("Input shape:", X.shape)
print("Input data:\n", X)

# Forward pass with automatic differentiation tracking
with tf.GradientTape() as tape:
    # Hidden layer
    z1 = tf.matmul(X, W1) + b1  # Linear transformation
    a1 = tf.nn.relu(z1)         # Activation function
    
    # Output layer
    z2 = tf.matmul(a1, W2) + b2  # Linear transformation
    output = tf.nn.softmax(z2)   # Softmax for probability distribution
    
    # Dummy loss for demonstration
    target = tf.constant([[1, 0], [0, 1]], dtype=tf.float32)
    loss = tf.reduce_mean(tf.keras.losses.categorical_crossentropy(target, output))

print(f"\nHidden layer output shape: {a1.shape}")
print(f"Final output shape: {output.shape}")
print(f"Output probabilities:\n{output}")
print(f"Loss: {loss}")

# Compute gradients
gradients = tape.gradient(loss, [W1, b1, W2, b2])
print(f"\nGradient shapes:")
for i, grad in enumerate(gradients):
    print(f"Gradient {i} shape: {grad.shape}")

print("\n✅ Complete TensorFlow basics tutorial finished!")
print("You now understand the fundamental mathematical operations in TensorFlow!")🔥❤️🌟

SyntaxError: invalid character '🔥' (U+1F525) (3669007531.py, line 48)