In [2]:
import tensorflow as tf

In [3]:
tensor_zero_dim = tf.constant(42)
print("0-D Tensor (Scalar):")
print(tensor_zero_dim)

0-D Tensor (Scalar):
tf.Tensor(42, shape=(), dtype=int32)


In [4]:
tensor_one_dim = tf.constant([1, 2, 3, 4, 5])
print("\n1-D Tensor (Vector):")
print(tensor_one_dim)


1-D Tensor (Vector):
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [7]:
tensor_two_dim = tf.constant([[1, 2.9, 3], [4, 5.8, 6], [7, 8, 9],[10, 11, 12]])
print("\n2-D Tensor (Matrix):")
print(tensor_two_dim)


2-D Tensor (Matrix):
tf.Tensor(
[[ 1.   2.9  3. ]
 [ 4.   5.8  6. ]
 [ 7.   8.   9. ]
 [10.  11.  12. ]], shape=(4, 3), dtype=float32)


In [8]:
tensor_three_dim = tf.constant([[[1, 2,7], [3, 4,9]], [[5, 6,7], [7, 8,8]], [[9, 10,11], [11, 12,12]]])
print("\n3-D Tensor:")
print(tensor_three_dim)


3-D Tensor:
tf.Tensor(
[[[ 1  2  7]
  [ 3  4  9]]

 [[ 5  6  7]
  [ 7  8  8]]

 [[ 9 10 11]
  [11 12 12]]], shape=(3, 2, 3), dtype=int32)


In [9]:
print(tensor_three_dim.shape)  # Output: (3, 2, 3)

(3, 2, 3)


In [10]:
tensor_four_dim = tf.constant([[[[1], [2]], [[3], [4]]],
                               [[[5], [6]], [[7], [8]]],
                                [[[9], [10]], [[11], [12]]],
                                [[[13], [14]], [[15], [16]]]])

print("\n4-D Tensor:")
print(tensor_four_dim)


4-D Tensor:
tf.Tensor(
[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]]


 [[[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]]], shape=(4, 2, 2, 1), dtype=int32)


In [11]:
# now i need a 4,3,3,2 tensor
tensor_five_dim = tf.constant([[[[1, 2], [3, 4], [5, 6]],
                                 [[7, 8], [9, 10], [11, 12]],
                                 [[13, 14], [15, 16], [17, 18]]],
                                
                                [[[19, 20], [21, 22], [23, 24]],
                                 [[25, 26], [27, 28], [29, 30]],
                                 [[31, 32], [33, 34], [35, 36]]],
                                
                                [[[37, 38], [39, 40], [41, 42]],
                                 [[43, 44], [45, 46], [47, 48]],
                                 [[49, 50], [51, 52], [53, 54]]],
                                
                                [[[55, 56], [57, 58], [59, 60]],
                                 [[61, 62], [63, 64], [65, 66]],
                                 [[67, 68], [69, 70], [71, 72]]]])

print("\n5-D Tensor:")
print(tensor_five_dim)
print(tensor_five_dim.shape)  # Output: (4, 3, 3, 2)


5-D Tensor:
tf.Tensor(
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]

  [[13 14]
   [15 16]
   [17 18]]]


 [[[19 20]
   [21 22]
   [23 24]]

  [[25 26]
   [27 28]
   [29 30]]

  [[31 32]
   [33 34]
   [35 36]]]


 [[[37 38]
   [39 40]
   [41 42]]

  [[43 44]
   [45 46]
   [47 48]]

  [[49 50]
   [51 52]
   [53 54]]]


 [[[55 56]
   [57 58]
   [59 60]]

  [[61 62]
   [63 64]
   [65 66]]

  [[67 68]
   [69 70]
   [71 72]]]], shape=(4, 3, 3, 2), dtype=int32)
(4, 3, 3, 2)


In [12]:
# now i need a 4,3,2,3  tensor
tensor_six_dim = tf.constant([[[[1, 2, 3], [4, 5, 6]],
                                 [[7, 8, 9], [10, 11, 12]],
                                 [[13, 14, 15], [16, 17, 18]]],
                                
                                [[[19, 20, 21], [22, 23, 24]],
                                 [[25, 26, 27], [28, 29, 30]],
                                 [[31, 32, 33], [34, 35, 36]]],
                                
                                [[[37, 38, 39], [40, 41, 42]],
                                 [[43, 44, 45], [46, 47, 48]],
                                 [[49, 50, 51], [52, 53, 54]]],
                                
                                [[[55, 56, 57], [58, 59, 60]],
                                 [[61, 62, 63], [64, 65, 66]],
                                 [[67, 68, 69], [70, 71, 72]]]])

print("\n6-D Tensor:")
print(tensor_six_dim)


6-D Tensor:
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]]

  [[25 26 27]
   [28 29 30]]

  [[31 32 33]
   [34 35 36]]]


 [[[37 38 39]
   [40 41 42]]

  [[43 44 45]
   [46 47 48]]

  [[49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]]

  [[61 62 63]
   [64 65 66]]

  [[67 68 69]
   [70 71 72]]]], shape=(4, 3, 2, 3), dtype=int32)


In [13]:
# boolean tensor
bool_tensor = tf.constant([[True, False, True], [False, True, False]])
print("\nBoolean Tensor:")
print(bool_tensor)


Boolean Tensor:
tf.Tensor(
[[ True False  True]
 [False  True False]], shape=(2, 3), dtype=bool)


In [15]:
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)
print("\nNumPy Array:")
print(numpy_array)
print("\nTensor from NumPy Array:")
print(tensor_from_numpy)


NumPy Array:
[[1 2 3]
 [4 5 6]]

Tensor from NumPy Array:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [16]:
eye_tensor = tf.eye(num_rows=4, num_columns=4,dtype=tf.dtypes.float32,name=None)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
