In [2]:
import tensorflow as tf

In [4]:
tensor_three_d = tf.constant([[[1, 2, 3],
                               [4, 5, 6]],
                              
                              [[7, 8, 9],
                               [10, 11, 12]],
                              
                              [[13, 14, 15],
                               [16, 17, 18]],
                              
                              [[19, 20, 21],
                               [22, 23, 24]]])

print(tensor_three_d.shape)  # Output: (4, 2, 3)

(4, 2, 3)


In [5]:
print(tf.expand_dims(tensor_three_d, axis=0))  # Shape: (1, 4, 2, 3)
print("================================")
print(tf.expand_dims(tensor_three_d, axis=1))  # Shape: (4, 1, 2, 3)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(1, 4, 2, 3), dtype=int32)
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]]]], shape=(4, 1, 2, 3), dtype=int32)


In [7]:
# Other examples of tensor functions can be added here
# squeeze, reshape, transpose, etc.
# already imported tensorflow as tf
tensor_three_d = tf.constant([[[1, 2, 3],
                               [4, 5, 6]],
                              
                              [[7, 8, 9],
                               [10, 11, 12]],
                              
                              [[13, 14, 15],
                               [16, 17, 18]],
                              
                              [[19, 20, 21],
                               [22, 23, 24]]])

print(f"Original tensor shape: {tensor_three_d.shape}")  # Output: (4, 2, 3)

# squeeze - Removes dimensions of size 1
# First, let's create a tensor with a dimension of size 1 to demonstrate squeeze
tensor_with_unit_dim = tf.expand_dims(tensor_three_d, axis=1)  # Shape: (4, 1, 2, 3)
print(f"Tensor with unit dimension shape: {tensor_with_unit_dim.shape}")
squeezed_tensor = tf.squeeze(tensor_with_unit_dim, axis=1)  # Removes the dimension of size 1
print(f"After squeeze axis 1: {squeezed_tensor.shape}")

print("================================")

# reshape - Changes the shape of the tensor
reshaped_tensor = tf.reshape(tensor_three_d, (2, 6, 2))  # Reshapes to (2, 6, 2)
print(f"Reshaped tensor shape: {reshaped_tensor.shape}")
print("Reshaped tensor:")
print(reshaped_tensor)

print("================================")

# transpose - Swaps dimensions
transposed_tensor = tf.transpose(tensor_three_d, perm=[2, 1, 0])  # Swaps dimensions
print(f"Transposed tensor shape: {transposed_tensor.shape}")
print("Transposed tensor:")
print(transposed_tensor)

Original tensor shape: (4, 2, 3)
Tensor with unit dimension shape: (4, 1, 2, 3)
After squeeze axis 1: (4, 2, 3)
Reshaped tensor shape: (2, 6, 2)
Reshaped tensor:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]], shape=(2, 6, 2), dtype=int32)
Transposed tensor shape: (3, 2, 4)
Transposed tensor:
tf.Tensor(
[[[ 1  7 13 19]
  [ 4 10 16 22]]

 [[ 2  8 14 20]
  [ 5 11 17 23]]

 [[ 3  9 15 21]
  [ 6 12 18 24]]], shape=(3, 2, 4), dtype=int32)


In [13]:
# tensor contenation 
tensor_a = tf.constant([[1, 2, 3],
                         [4, 5, 6]])

tensor_b = tf.constant([[7, 8, 9],
                         [10, 11, 12]])

concatenated_tensor = tf.concat([tensor_a, tensor_b], axis=1)  # Concatenate along columns
print(f"Concatenated tensor shape: {concatenated_tensor.shape}")

Concatenated tensor shape: (2, 6)


In [14]:
tf.stack([tensor_a, tensor_b], axis=0)  # Stacks tensors along a new dimension

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [18]:
tf.stack([tensor_a, tensor_b], axis=2)  # Stacks tensors along a new dimension

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [21]:
# stacking 4 by 3 tensors
tensor_c = tf.constant([[1, 2, 3],
                         [4, 5, 6],
                          [7, 8, 9],
                          [10, 11, 12]])

tensor_d = tf.constant([[13, 14, 15],
                         [16, 17, 18],  
                         [19, 20, 21],
                         [22, 23, 24]])

stacked_tensors = tf.stack([tensor_c, tensor_d], axis=1)  # Stacks along a new dimension
print(f"Stacked tensor shape (axis=1): {stacked_tensors.shape}")

Stacked tensor shape (axis=1): (4, 2, 3)


In [22]:
stacked_tensors

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]], dtype=int32)>

In [23]:
# now let talk about padding and cropping tensors
#  --- IGNORE ---
tf.pad(tensor_a, paddings=[[1, 1], [2, 2]], mode='CONSTANT', constant_values=0)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [26]:
tf.pad(tensor_d, paddings=[[3, 2], [2, 2]], mode='CONSTANT', constant_values=0)

<tf.Tensor: shape=(9, 7), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 13, 14, 15,  0,  0],
       [ 0,  0, 16, 17, 18,  0,  0],
       [ 0,  0, 19, 20, 21,  0,  0],
       [ 0,  0, 22, 23, 24,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int32)>

In [27]:
tf.pad(tensor_d, paddings=[[1, 2], [2, 2]], mode='REFLECT', constant_values=0)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[18, 17, 16, 17, 18, 17, 16],
       [15, 14, 13, 14, 15, 14, 13],
       [18, 17, 16, 17, 18, 17, 16],
       [21, 20, 19, 20, 21, 20, 19],
       [24, 23, 22, 23, 24, 23, 22],
       [21, 20, 19, 20, 21, 20, 19],
       [18, 17, 16, 17, 18, 17, 16]], dtype=int32)>

In [28]:
tf.pad(tensor_c, paddings=[[1, 2], [2, 2]], mode='SYMMETRIC', constant_values=0)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[ 2,  1,  1,  2,  3,  3,  2],
       [ 2,  1,  1,  2,  3,  3,  2],
       [ 5,  4,  4,  5,  6,  6,  5],
       [ 8,  7,  7,  8,  9,  9,  8],
       [11, 10, 10, 11, 12, 12, 11],
       [11, 10, 10, 11, 12, 12, 11],
       [ 8,  7,  7,  8,  9,  9,  8]], dtype=int32)>

In [29]:
# tensor cropping can be done using tf.slice or tensor indexing
# ten
#  --- IGNORE ---
tf.slice(tensor_d, begin=[1, 1], size=[2, 2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 18],
       [20, 21]], dtype=int32)>

In [30]:
# tensor gathering can be done using tf.gather or tf.gather_nd
#  --- IGNORE ---
tf.gather(tensor_d, indices=[0, 2], axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 14, 15],
       [19, 20, 21]], dtype=int32)>